-- seed.sql - Popula o banco com palavras pré-validadas
-- Uso: docker exec -i forca-db mysql -uroot -proot forca < seed.sql

USE forca;

INSERT IGNORE INTO Words (word, `used`) VALUES
('cachorro', false),
('teclado', false),
('floresta', false),
('computador', false),
('telefone', false),
('montanha', false),
('aventura', false),
('elefante', false),
('diamante', false),
('bicicleta', false),
('misterio', false),
('melancia', false),
('fotografia', false),
('maravilha', false),
('horizonte', false),
('esmeralda', false),
('chocolate', false),
('borboleta', false),
('esperanca', false),
('universo', false),
('liberdade', false),
('felicidade', false),
('tartaruga', false),
('dinossauro', false),
('biblioteca', false),
('arquitetura', false),
('estudante', false),
('cachoeira', false),
('brinquedo', false),
('carruagem', false),
('primavera', false),
('travesseiro', false),
('escorpiao', false),
('alicerce', false),
('vestimenta', false),
('constatar', false),
('vislumbrar', false),
('esclarecer', false),
('transporte', false),
('desenvolver', false),
('observatorio', false),
('calendário', false),
('instrumento', false),
('professor', false),
('engenheiro', false),
('agricultor', false),
('paisagem', false),
('movimento', false),
('fronteira', false),
('continente', false);

SELECT CONCAT('✅ Seed concluído! Total de palavras: ', COUNT(*)) AS status FROM Words;
