name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      
      - name: Pull and Build Docker containers
        run: |
          docker-compose pull  
          docker-compose up --build -d  
      
      - name: Wait for containers to be ready
        run: sleep 15  

      - name: Run Docker Compose to start DB
        run: docker-compose -f docker-compose.yml up -d db

      - name: Run Docker Compose for backend-test
        run: docker-compose -f docker-compose.yml up -d backend-test

      # Adicione outras etapas de teste ou build conforme necessário
