name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Ou a sua branch de trabalho

jobs:
  build:
    runs-on: ubuntu-latest  # Ou qualquer outro runner que você esteja usando

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verifica a instalação do Docker Compose

      - name: Run Docker Compose to start DB
        run: docker-compose -f docker-compose.yml up -d db

      - name: Run Docker Compose for backend-test
        run: docker-compose -f docker-compose.yml up -d backend-test

      # Adicione outras etapas de teste ou build conforme necessário
