name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: forca
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" 
          
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and run Docker containers
      run: |
        docker-compose -f docker-compose.yml up -d db
        docker-compose -f docker-compose.yml up -d backend-test
          
    - name: Run tests
      run: |
        docker-compose -f docker-compose.yml exec backend-test npm test
          
    - name: Tear down Docker containers
      run: |
        docker-compose -f docker-compose.yml down
